apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus  
  namespace: monitoring
spec:
  releaseName: prometheus
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '45.7.1'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki:3100
          ## Needed if loki auth is enabled
          # jsonData:
          #   httpHeaderName1: 'X-Scope-OrgID'
          # secureJsonData:
          #   httpHeaderValue1: '1' 