apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-explorer
  namespace: apps
spec:
  selector:
    matchLabels:
      app: file-explorer
  template:
    metadata:
      labels:
        app: file-explorer
    spec:
      containers:
        - image: filebrowser/filebrowser:latest
          volumeMounts:
            - mountPath: /srv/pypi
              name: pypi
            - mountPath: /srv/postgres
              name: postgres
            - mountPath: /srv/redis
              name: redis
            - mountPath: /srv/wireguard
              name: wireguard
            - mountPath: /srv/tekkit2
              name: tekkit2
          name: file-explorer
      volumes:
      - name: pypi
        persistentVolumeClaim:
          claimName: pypi-server
      - name: postgres
        persistentVolumeClaim:
          claimName: data-postgres-0
      - name: redis
        persistentVolumeClaim:
          claimName: redis-data-redis-master-0
      - name: wireguard
        persistentVolumeClaim:
          claimName: wireguard-pvc
      - name: tekkit2
        persistentVolumeClaim:
          claimName: tekkit2
---
apiVersion: v1
kind: Service
metadata:
  name: file-explorer
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: file-explorer
  ports:
    - name: ui
      port: 80
      protocol: TCP
      targetPort: 80