apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-explorer
  namespace: apps
spec:
  selector:
    matchLabels:
      app: file-explorer
  template:
    metadata:
      labels:
        app: file-explorer
    spec:
      tolerations:
      - effect: NoSchedule
        key: networkmode
        operator: Equal
        value: host
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: networkmode
                operator: In
                values:
                - host   
      containers:
        - image: filebrowser/filebrowser:latest
          volumeMounts:
            - mountPath: /srv/pypi
              name: pypi
            - mountPath: /srv/postgres
              name: postgres
            - mountPath: /srv/redis
              name: redis
            - mountPath: /srv/pgadmin
              name: pgadmin
            - mountPath: /srv/wireguard-ui
              name: wireguard-ui
            - mountPath: /srv/wireguard
              name: wireguard

          name: file-explorer
      volumes:
      - name: pypi
        persistentVolumeClaim:
          claimName: pypi-server
      - name: postgres
        persistentVolumeClaim:
          claimName: data-postgres-0
      - name: redis
        persistentVolumeClaim:
          claimName: redis-data-redis-master-0
      - name: pgadmin
        persistentVolumeClaim:
          claimName: pgadmin-pgadmin4
      - name: wireguard-ui
        persistentVolumeClaim:
          claimName: wireguard-ui-db
      - name: wireguard
        persistentVolumeClaim:
          claimName: wireguard-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-explorer
  namespace: apps
spec:
  type: NodePort
  selector:
    app: file-explorer
  ports:
    - name: ui
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31503