apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: istio-operator
      version: "1.13.3"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    hub: docker.io/istio
    tag: "1.13.3"
    operator:
      profile: default  # You can choose a different profile based on your needs: default, demo, minimal, etc.

---

apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
