apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  releaseName: minecraft
  interval: 1m
  chart:
    spec:
      chart: minecraft
      version: '4.7.3'
      sourceRef:
        kind: HelmRepository
        name: minecraft
        namespace: flux-system
  values:
    minecraftServer: 
      eula: true
    persistence:
      dataDir:
        enabled: true