apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: "https://istio-release.storage.googleapis.com/charts"

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  interval: 1m
  chart:
    spec:
      chart: istio-operator
      interval: 1m
      version: "1.13.3"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    meshConfig:
      enablePrometheusMerge: true
    components:
      base:
        enabled: true
      pilot:
        enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: istiod
              patches:
                - path: spec.template.metadata.annotations # Is this the best way?
                  value: { prometheus.io/scrape: 'true', prometheus.io/path: '/stats/prometheus', prometheus.io/port: '15014' }


---


# Sample Tracing implementaion with jager
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: istio-base
#   namespace: istio-system
# spec:
#   values:
#     pilot:
#       traceSampling: 1.0
#     global:
#       tracer:
#         zipkin:
#           address: jaeger-collector.monitoring:9411


---

# If we enable that, we will enforce SSL handshake on every
# connection that goes through envoy/istio-proxy
# TODO: Look into that
# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: default
#   namespace: istio-system
# spec:
#   mtls:
#     mode: STRICT

---

# advanced traffic routing rules such as canaries, blue-green deployments, or traffic mirroring
# apiVersion: networking.istio.io/v1beta1
# kind: Gateway
# metadata:
#   name: <gateway-service-name>
#   namespace: <gateway-namespace-name>
# spec:
#   selector:
#     istio: ingressgateway  # use Istio's default?
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - "thewatergategroups.com"
#   - port:
#       number: 443
#       name: https
#       protocol: HTTPs
#     hosts:
#     - "thewatergategroups.com"

---

# Implement retries, circuit breakers, and timeouts to improve the resiliency of your service communications.
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: <vs-service-name>
#   namespace: <vs-namespace-name>
# spec:
#   hosts:
#   - <service-name>
#   http:
#   - route:
#     - destination:
#         host: <service-name>
#     retries:
#       attempts: 3
#       perTryTimeout: 2s
#       retryOn: 5xx,connect-failure,refused-stream
