apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio
resources:
- istio.yaml

kustomization/istio                           	                 	False    	False  	kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'istio.yaml': invalid document separator: ----': must build at directory: '/tmp/kustomization-2547495740/deployments/home/istio/istio.yaml': file is not directory	
