apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pypi-server
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: pypi-server
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pypi-server