apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  releaseName: rook-ceph-cluster
  interval: 1m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: '1.13.2'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    timeout: 30s
    remediation:
      retries: 1
      strategy: rollback
  values:
    clusterName: rook-ceph
    cephClusterSpec:
      mon:
        count: 1
      mgr:
        count: 1
      logCollector:
        enabled: false
      placement:
        osd:
          tolerations:
          - key: networkmode
            operator: Equals
            value: host
      storage: 
        useAllNodes: true
        useAllDevices: true
      resources:
        mon:
          limits: 
            cpu: 1000m
            memory: 1Gi
          requests: 
            cpu: 1000m
            memory: 1Gi
        osd:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
    cephObjectStores: {}
    cephBlockPools: {}
    cephFileSystems:
      - name: filesystem 
        spec:
          metadataPool:
            replicated:
              size: 1
          dataPools:
            - name: replicated
              replicated:
                size: 1
          preserveFilesystemOnDelete: true
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              limits:
                cpu: "1000m"
                memory: "512Mi"
              requests:
                cpu: "1000m"
                memory: "512Mi"
        storageClass:
          enabled: true
          isDefault: true
          mountOptions: []
          allowedTopologies: []
          name: rook-cephfs
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    allowVolumeExpansion: true
    reclaimPolicy: Delete