apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Dev project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/Wednesday-Vibes/topical.git
  - https://github.com/Wednesday-Vibes/keycloak.git
  - https://github.com/Wednesday-Vibes/vpn-frontend.git
  - https://github.com/Wednesday-Vibes/local-development.git
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
