apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: domain-management
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: "1.14.5"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: domain-management
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: "7.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    provider: aws
    txtOwnerId: Z061744026X1CUF71V2PH
    domainFilters:
      - thewatergategroups.com
    aws:
      preferCNAME: true
      region: eu-west-2
      credentials:
        accessKeyIDSecretRef:
          name: domain-management-creds
          key: aws_access_key_id
        secretAccessKeySecretRef:
          name: domain-management-creds
          key: aws_secret_access_key
    policy: sync
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7979"  # Default port for external-dns metrics
