apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-explorer
  namespace: apps
spec:
  selector:
    matchLabels:
      app: file-explorer
  template:
    metadata:
      labels:
        app: file-explorer
    spec:
      tolerations:
      - effect: PreferNoSchedule
        key: networkmode
        operator: Equal
        value: host
      containers:
        - image: filebrowser/filebrowser:latest
          volumeMounts:
            - mountPath: /srv/volume1
              name: volume1
            - mountPath: /srv/volume2
              name: volume2
            - mountPath: /srv/volume3
              name: volume3
            - mountPath: /srv/volume4
              name: volume4
          name: file-explorer
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: pypi-server
      - name: volume2
        persistentVolumeClaim:
          claimName: data-postgres-0
      - name: volume3
        persistentVolumeClaim:
          claimName: redis-data-redis-master-0
      - name: volume4
        persistentVolumeClaim:
          claimName: pgadmin-pgadmin4

---
apiVersion: v1
kind: Service
metadata:
  name: file-explorer
  namespace: apps
spec:
  type: NodePort
  selector:
    app: file-explorer
  ports:
    - name: ui
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31503