apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator  
  namespace: apps
spec:
  releaseName: postgres-operator
  interval: 1m
  chart:
    spec:
      chart: postgres-operator
      version: '1.10.1'
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-charts
        namespace: flux-system

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui  
  namespace: apps
spec:
  releaseName: postgres-operator-ui
  interval: 1m
  chart:
    spec:
      chart: postgres-operator-ui
      version: '1.10.1'
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui-charts
        namespace: flux-system
---
kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "postgres"
  namespace: "apps"
  labels:
    team: apps

spec:
  teamId: "apps"
  postgresql:
    version: "15"
  numberOfInstances: 1
  volume:
    size: "10Gi"

  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi