kind: postgresql
apiVersion: acid.zalan.do/v1

metadata:
  name: postgres
  namespace: apps
  labels:
    team: apps

spec:
  teamId: apps
  postgresql:
    version: "15"
  numberOfInstances: 1
  volume:
    size: 10Gi
    
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi