kind: postgresql
apiVersion: acid.zalan.do/v1

metadata:
  name: postgres
  namespace: apps
  labels:
    team: apps

spec:
  teamId: apps
  postgresql:
    version: "15"
  numberOfInstances: 1
  volume:
    size: 10Gi
    storageClass: microk8s-hostpath
  allowedSourceRanges: ["0.0.0.0/0"]
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin  
  namespace: apps
spec:
  releaseName: pgadmin
  interval: 1m
  chart:
    spec:
      chart: pgadmin4
      version: '1.18.5'
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 31000