apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: apps
spec:
  releaseName: postgres
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: '13.2.24'
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    fullnameOverride: postgres
    auth:
      enablePostgresUser: true
    architecture: standalone
    global:
      storageClass: microk8s-hostpath
    primary:
      service:
        type: NodePort
        nodePorts:
          postgresql: 31000
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin  
  namespace: apps
spec:
  releaseName: pgadmin
  interval: 1m
  chart:
    spec:
      chart: pgadmin4
      version: '1.18.5'
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
  values:
    service:
      type: NodePort
      nodePort: 31001

