apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pypi-server  
  namespace: apps
spec:
  releaseName: pypi-server
  interval: 1m
  chart:
    spec:
      chart: pypi-server
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: cgsimmons-charts
        namespace: flux-system
  values:
    pod:
      replicas: 1
    persistence:
      storageClassName: rook-cephfs
---
apiVersion: v1
kind: Service
metadata:
  name: pypi-external
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: pypi-server
    app.kubernetes.io/name: pypi-server
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: 30500