apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis  
  namespace: apps
spec:
  releaseName: redis
  interval: 1m
  chart:
    spec:
      chart: redis
      version: '18.5.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    architecture: standalone 