apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authapi
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/authapi
    repoURL: 'https://github.com/thewatergategroups/authapi.git'
    targetRevision: dev
  project: apps
