---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: private-repo-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgCGX8ylYZmMsSB+5bRGBT54jR9jpePpIB/YNkzPtVjeBp2ZJ478kxuGlpWIN8odHYAROonE9w9Om+aieQCCcTQ8y3orPYYBmdmQMnbeMYAmsV+IMDhp1BU9hlQm3n1ljM2kDNT9TCPF0GqKkXtZM0E1KUq423ZPLY51aX8oi6OjV7kL3qahtJN2u/ykL70slRFVlVshd+Be7/EP8tAkqZjmUB1OsKcFxOjp8R346uqvC+TYlzzd/2XPp78WaNI+NWAH7rCyCd8zcfL9WUXfIrxJJ/LzET/V8j860UtXb4t9RvTDca7FGPppXNtqwhWHh7mk1wDVKcmepAPJhBConILEnuqKAysW1gCRDnjtpk/gxWiLqP0sdH5Ekrs8sEiWB8Y2kHkpNdSXsYMKyGxvPtm7jMX1Ohm2miyN14g7/hC/zY4+rwIsO36W2+RezmAIE+5d7uiorXsFmxTk4EyyLh069o/bmwyfrmbc7I+AFdfJ5t2BKHNcW1Q+7LkUmM7RqFA+PmxSotNypwGzsiFY2zezxBXSt98jcUDDZLL6VPEIUMLFy4ZFD/OYv1cGVrDfInICasatY0ELML5OqIYoVcgRFFYIQxHNxstBsNzuIDsStSMt64lZr9TI9xJvLjMDoe3bC6XMm+Vl8r5xUcnlEpxYx4xMv59uR2lrxFcH9zvU1ifBEJJ1F8DsC4LiKyKGsYvStH3uoq2PZLyhF6znovHzCe4MBACletx3Gj9To6K75yZqMVdzRK7U
    type: AgACxeXTA9Q0LIHz+rnxRvlEpgANaaWjbUMb6YWVAaYFlxBiwlmCLguV3YnbuC35jNAhSoT9FbpuYyCCcXyWd+VBlEKo88j6uJE4bIoWQxCBMoi4MR32ofBGRDtsHD309eOgYDRq4sdP7Dep/6oAx7NAEJl18N38nvuSldRfBO5jCq0mAVZRN7M+9XWLsDj7uUwNnflK0if3hlNvizzfRenfTDHFtWUxykHLpK83StQbduAYNR0zDlJNvE9Kgg59A7yxqrLHP+H/vaGuRvMge8WweiDqvTNOY7xN16+sASwVUS9WPaudS60FdRoUoJpY3cGDXl8sgDYtU+5+J4n7WbYzNtsEJqktJX2SbLfW3w1MJ3WDAecRtJpiPd/KipsCxnLveYeTDhLrhG0HKRCt/JiG3DiAkdjGConX7z5obJYJzlwOLSlHfpsdgeEXFUCvyR6tCA/ylULH1xkWj06ipKb1j18L+MCYyvN3v+E7WtC531zptf/sgQPG4zQqtcntQDkyirT3YkLNKedT8E+kLrkU/MSY1xRa6krGp6lo0G/XMvshz/ZDPv95Wokape9+QdJNRKifvrEc9Ca+w6LeXbjrske7BT4JCy3HOwhwIr0oXX4HQ7Qq2lLv2CMriJqHMO2z8s8F/pSLdMmjNfY7hti3ME+nxppn9Qm8iuhk9BPeZUK5pAy6TRJvCIr2JNkhsXy0dk0=
    url: AgDP1xrh56F+/WZXPMTPlW1J1+faK1uuE8iKXLdVuqgNdb9bqW8RxiHK6p/LSYRVFaC5PZn9Nf+cGb+aMwSOZarsupFyxaxV7CCKYIHNlJZjCmJKSewtX5Pj3E76VGmXjBRXU1nLVuPpXthFS/WpvOfCu2WVw2ma2IUK8MuGBqHwQIm1M1ftP3TEUph1pyRJ1Flw8dcRVP2AswotIbYa4yuSlfj0yyNWCCg1M/RCOUww2nxKos2YFR7omZH3picI9FDLsM1uSUyq71nbGLCRt5xjJ0Oq+Tt0Q4jUe1SsBcz+nFcbmUCO3kvgGnHuahaWh2szoQZUVt2pBQwTTqx0r+7mveHXS6KfBAlarg8edhOwBobN2ksMZNNoXlowW7uzQfyqVvRIkMynqnLCv5PknbwDPhAFB4lE2INt3U0sVQ0b1F3FCYDQVYIVp14nBJIsQM42qsws0HnSxvinex2DZz/vB02mV7Nd7m2F+GhIXM6/DwrmfY5mktKdR/Quy6dUZrn08IZJwJaKDx6lKWoyTZgWrKQDmVZuDMlH9w5XKMPKWBp+6JhN9oR27MHVm1/Xm6oL3LYf0st4Fo5BmJr/m2ugDaEoeNm2bLQhYB9JcLgWmMeCb0qaXpi4Pi6bfM6Ml6+2f6Hyg004OW573Rc7m+jyEK3/v/2xbRnElKRZPVVV55D64U2qsb9roKsSpowYbbRN/PG24vQJSS/RTyxUhL0gsPx+A7I0w05vjrdhaw==
    username: AgBkOfnPGCLnqqrm+XPEte+0yMOGL+HNNjA6YEgUkd4N0k8sYFyS6Kgdn4FwcC1eSpaSGYXwQjZl8xNZD6Z2Mh/kLYKsmdwAjJfXezmH3UTlHYzpIO6DDKP3N0rKWjyKmaUbN299GvwG6ujFWssAl1u7atHttht0TvLK20VZYXfz9q+JooZ8REwyfrjkItKlnkDQ3ue+H3ePFCt9sBvMmUwfBdcURr3UyxKmz73calUaGenM+RmU321LU4w/JryHwpnioeHWJs5qUR5jzRaF4cVKGIJi65P6e+CfRnCOX31+7milqWVwc6136lFEl3Xlrbx2qH1ixjbUmVXpzM8rxksoHgjqvEM+Gkq839pBSSh1rkr/tjDra2drIFLTgzdJnzFKgWKVrrTSpenz1ig1UxDOrvy4cBrlDp9xj2Nu3ORRoKuaqJTWOCf9AOIA+ucS2M1uDPCrU5dexwnvZD6NUIylG5lRUdtH6izt9cV88Z3M6bcNE3EYOIXHxP+J/D1RJ6XerXNOpAnnJrbogZ0QB4iwm57aZ9UqXhkMQ18sAwdLt5bDY0XjX4mQeoMkA2UVzE/kAkDXcLr6jmQh8nPdN8ZKRyGyr3+jcPprNYCTaCObj/c2dYsqv2Mi4ZvAL/D4/k48Ollck5fvWhw7y6yT21eN0juYNi6ul9MUp+qnL8DvG3jeAtSFePcYllB/KyysVAeeOUyduX/CHi0w7A==
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: private-repo-creds
      namespace: argocd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: private-repo-creds-2
  namespace: argocd
spec:
  encryptedData:
    password: AgAF0AD2kB1uLZjAVNOZrP4vfE4ehksUTnMlZRLEqHWcOcZ81r4T7mTzeWu3xagiLyT6FQPlfMWgsC55zkDfoZEsSUBeM6zZ1fH1cwodB97sLYP2IsBIZ+qdEGhuYXD97YpU/66iWvry848UeqYAGvr3HcP6wxLAz2NnOYBtELSuED3oNLMhc4vm3YnKNNvP4j9HDsSK/kzIUYNbuVf67A/BXjQgAhG/edlMkXBZv2r6EhzWRCpOTmfT6wpQhDgDeGTrvVgyREwzKIluHI7NQgwx9of8M10hPeWds+0RGcKYu602lzXPmYZsQTVNbOPauZHwHl1tz5fs3BuaeXN76MCvx093vu96FCkg+YvWQ0oblH8hLP2vVQamEu3TcCtmuwlz50W4E1u4vBQrGAhUnwT+lfTWypeAkeGs/ZY0nzLohhY2gbNgizLEVoggms/YOaCUc/+2UMWnamX8UbtByVS9iWeVayzCdV91Ad6U3fPRoA2sigDDTe1fw6wW8RiMM5sSJJybEMny9FkxEnFb/6wW0KT/BQRV/fOE+SmRmIwRpdw/7PNi4JtzO1gf0Tp5E9DVX6tmTfAOv0K9ge5FiBA9NXofQauZ1C2yDm0S25l/7CxF/4CJd5ywnfrdqWAtUakdVcuJy/0Wiq3/BHqxFeNO10UxvE3mPQq/DF7V5ei2bv48efjGyBTCXrny2xWEYLIrhzB+YIv+2M2zssbQ99iWGJ1pUOg6QRmgHsI8x6seSmz9qMLhgc8X
    type: AgC86nYDcTyvEs6nbIhb1ESigKckTQQf8TA2kxsBPC/9u+vkwiEhoLxdf3OsrXmgvmDOxdTufDWoZYAijlhXeCHc8IXSH7DSiFfwlOWl7dbu9dF68Y9LuQ8n13lNtphMTT2CUMTttgjhzaMakDxhvxSJKIbreBKVQEt3PdDc3T0NLFq3/Oomn7n4tzElC703rzvQmMSgQCVB03udWGH75DVnOyxJNWbzX+k4SthQ1LaSqCKm3r3UFviFZE4EFdPM4i4x6YALbFg8MaxPMOy76kLlr0WUA3tyN8XvLZUDvTIaM9Y7OTTJB24tRwW6huAxxNZeXw4HE9wJC3UClZvEgCrjcseoWQIOqFElW2LmugjJW73ONnVQibWn61LFwCTuKJBuhvUKTvzbj9b03jVXBYIVELluWn6d9EuZDrHx/kGC6o87NsofGZ/g2FxQEVfv4i+hBhh4ejnAdGmTnlu1y9ag6zEjOz22LjmOxXz6+SA0JbqpNFRk+Ah+pUdJR1SBpriy/uSQuMChIWb7mBeAvhemQQTlc1DCpXsVOLFrYtz1Ppm/YBjhlPm3A92FZKRXHazd8pJqXGiVhZI7IbOnYzdK+VEtTyfY46z4y7aOkdNOFq2lg4PGZoZezTWyQjunSfvuQT85tkkQttQ338CQ9zzpgscVjKd/1AAS5MYY6HSH4jrWlgmuK6y004QDrk1icgK8yjs=
    url: AgBb0psrSKV9IQMeUPWopEYlcseXqEOl8LWawaysnHOXbbHSjf1BwnCbDKSlrDwsFUCcliBuXhJmPxPLqn3V2ODMP9F1rAgenSg9lcp1JA0LUq8IUGcZ+K0vAkw1kXnibna1FRBNLDDoOtj5Zzw84bUo8aeW7R7pXgaPb/5wegLT8q1viFZZQSJyiE4XmDN7JXCTfxIokqjzp1Vjfh6au/HLtuJbSAil8T4hzpubtxug1JSruRD6U8OdutzTwUmz9Q6N3zbbLHpW7VA7UjtFei1k7Rf/eF7u57TRQop8ir2GaTWg2S72xyMTtmHoUUD9NlmJ2ftQHS/npbBT9xID7Juxz+8CQBjn1M9/zc6soq09ZXwGqY+Ekiv8MengbYF/7+iO0JMpJx0kf/Fh/5VLJlvW18Jm8SLMICymOYu/aPxJ7DaEkXAM1svAJOVnWxJFB0xD/ScvOGuRRsqJHTrVYcyBHkT8eUvFcB4NY9C4Q+g1nUuiziiYsYzb0ERYruhr5NzAU7hDVb6egYyHuyoSwKjXZnLIUVLXDnNA7sN5FiD36KlxW/OYDu9y53GNysvNdl5VUkDQN0ycZMNeSNB2Y7tKaK4aCKCvyHIqo8AwkiJW8SqJ3j+5n3tvzp3LyiGDWywEd2FNxNW7Cl27zLoCtH5ZQHrLZRqQx89RiwDmD1Groe/f2Iz4RrWYypaSiHaBDNDXzVCf5sTdP+5xu+pgIwUQuZr66E0fBXWrFrHnew==
    username: AgCaT7Xg+FvuEkqBczTUgvXWPHTGIMTprYmVCTLFCEbOO4Q9Fs5YEerPv8Yd9K329ebAVKL259G+YCN86iU4m/Nawbhx51QNsXohIZG3yQQwIc38CdQt0mkecQ24xZXa8uI22k92oqVilCkWQeETjqHVmzULapt5Xc3iB6+CDOYY689AOR2UQ3MNMcRLT+HIil1/r3mj5/zC6E5WkFL5/v/6x6jAAypFdFoSHCqxG7DF9X7erIg3+M1Nvg00lJv3J+f3ADyDIRxdyMYDyHUFDHqH6ZwHZOk1Gald0DE/Axz4Wdd7Iu1uPG3R4JlN48HIFMf6Uft/qxzwOc7IB/GYzYisbYYVeyPc/Bdnqx6B3Cdv8KtRlI0ZYtF5Om+ItHSk5N7DBIq8x5x0PFx/Fn06PCDncnRt5j3l8tV6adWpwcozC0hQx9M8bmP4WQGVStVUML25OHwTXaVn9Hnidg9MFn2gOM1tdFtDgEm5rBbEzo1LWAcFZKTc+R/NtYJ2qaSxnjcDMAW+0q/TmJJzQbejMqgieFSoHszT/grern5f/TR8h/GxV0Su7/p9++VQmRyHw+sKocGtLEGHOWpStB1fxxs2ttARr21SDmD/0VqS3F9BkgApMTud7oedpi6gjczwJkdMUpbncq87Qem/GvpigaKzp2n6TjT9qQu2zPfCPmVYQopvhXDHRtKhEkkYCrr/rOdSBxHtoBXIWiB+FQ==
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: private-repo-creds-2
      namespace: argocd

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: watergate-repo-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgDOh3w/iK6D9S5mJK1nUiUBg6JC3ujBSPibPEXqC/ejF7n1Z/dhK97hk4nk8S7FkN/HrAoTEJ5AGbR0Ro1POoTyDPyFH5haTGkJkXsoO2Qn7cPPiaob2wOKLN3OD6L7GGI8FYLwbYBJODDJBEymTLihJo/5qw3wzeXhQNjmz2/wCCIA4XFjpNzrkSFFX8WE+WOxibzimIl1eRg9jJMqPP+9ZGsKGcCLJ5KXCSJC3mrjdDvLS60wckfDWtyjoYXruYIPYf9mlnLSrFOUvGmGGu3ZvZVPL++n3HG79AnL4pSYeNffrDpeK4fwHLBUITn5FqoHM7moGJhbDIxi7UT/bDNFp2cu96h9WY29x/YGcOicfkH//Ddyc767sO/xl3D2mYpCxfP2o8AZT5a+VbeWhIuo00YlH7Q2a5uhp+k9gpMmWMUgNZ3DRmJ9o/kjjxPvgUVanq3Pp20F5LkC79iesZOJR6g/6St1tBL32JX9DgeEOE9FTQNPwNgt+WpjHf/k2jLswBTPxnZD5X5wFhXJcNy2DE17Zk/nOYxXb7vDWuSpvoX/0H8MiPudGZl4/GgN/Qd3Gr3y8cCYQcI+UMXpm9ky73HG0q7hFgtybdR8yPFU46ql6GnaWGOjTZ9ch/0W6Ptes33J9O4O54i9Onif5IauyGie8TJzUNO4tkqVa6QVDAA93Vm46efCjM5wTnn47lUzLwKOH/MrgIbf1agvZUGFts6NTQbGJutRBtcHbOQXvdD/yg316wB0
    type: AgC3gSZp+rUMIBUD3etz1AbV9NfDqhaVWD8uJwnMH5mJj/uqPFpxQOfY3koDXNcH70ng90QpmbeFwzHKDUm0gCzD/5BnlfILhwN08eDjLwNxQfgWS0q4AH9nWIpHgvK9Z6LG4SVmL0PHCL5lTvdxQJDkCSZ/xSTDz/rausvX+PnF54xYhx0kG+Z7FuFeY5aR1+OmgPyn+/Y/hgcaiwPPWsg3OgKuQ1en5QcsQ/ygKRS5yD/5dC5xZ0m5r5tCQBdsT8TPFwPRglH4Lniae8MxWkIXTSL0bbPHlTMk0iVX3Hu3aFx6kRHzsMNJ9gLGqMAo0j5xViG/5TOwt1N/8axvjgwNofUlp7/GPviTKyQ7HjrPJhIS6ZRBf1+Kyaaid5GYejiV7Ovp0AynSfLKyna/Iwaz3zMKMcAwyAe8FjSzV4ZHOzPOM1lT3JpwNUt4sq5dqSW7Vjh4mMg9LZL69Y5OEe7MGEksM/YLCpIGNL7/13YNUtTsWhjZDM3MOaIEgBDKFCWEikwI/UR0D8GmBdz5n4H04Gm9jm3b/615/+gmTes8Fzkhf95eo7cQtiTF1maYepddUfSFnWM1+XQnL+BM6241M2oysSh3dCEwAIUd4kSZbR39dCUBwz7GuaSeTeUDCgKoyPOy75Ntfo7YJuEezVZE4eBb2VWbNAXSGuRx6CxaSWW2a3uKIGWw6Yi1wgoNJlIG/QY=
    url: AgBaqtTovHRresiPEpLFfj2oVTgi9fJGBISMrRi5LqX7vrR66550TxTBDH6SlSFPac4JD2S/a5tvDtCLf3lV7WXcBO/o2sWS7bX3s2NMPKbL/3oBqXEZ2P48rF8JQtDY8A9mQVpBFHx5CMel+MTnczDpbds5HK5WTmQiDvZ7hNuSXxAwBydB09/Vex9wAizKC8btfiieRGrIG0/AYyHpEUbYCIGQEr0zPkA5rzwpUJmWL0mdjL+AjDNR/UybmDoESMySkkVOldT9vWGB8VY7+4wV8cb5Z6agZuy7LqBkqLPgPJhhVnMbWyL3YPSLtplHsAEOhRKkiCPHehaeqoeXKYETIiJMMWhuTisY1p69H0RYygPiPhTTo6pybrozS2+aGXbGMzks8/2o7IAG0aAn3sw8gYuUB44NPc7uMup6geSneTDMOS1jQvi3gnlYSv0MouYKAZWfW4HWYN8cZgVWXKWO+YBMwYhsvAuOzuzdLQ5Io0G14f1eMLCAF4aTZiOID4LMqa1S4MFRbbfPVuNGZp+7pfTNG+wZ/HH3IWouxLoWEBdYZaAQugP6Dk9EohMLJ/tmOz1nLPmzEZGmrqFmcFDSCT+ou4ub3XtF1mqA2KMbrvoMyIEtDjRmqXXLnPSjVmtlHvW39rUr9hEaNzQ3BGBwFIauuizlHeYuD96t7DNfffXw7Rk3MEfBMS4vsIBoVjAfRNlwdhdsdchhA+Ht8uOrkYaFC8LPsDltkC5pTlNwr2Wj7kD6
    username: AgB9spwkArTfvQSmtDLAxMCgxUKAgikEXhs/I4IVbQIhTCJyFXkdaqjh09akvXuttGh2DPct2n/HvLubCr4HWG3v5SupXXZij3kN3jCoOv5rONgsSgoTcO9q+iROzMxL3GdR6FQoBC4xtDnjg6+wV0sn5JkBL/4ULjbHD+LBwc5sH0bQGrwrOj+Cr2DsuV5h14sTJKj4MlXeVUImPa2XhV6pH6EYRG4eb0I76+N95b9IVl4U8yWIMsJv1RTECYkg33oWJiv1NMtw7UfQ23YvOQRm1paKqUApm2uVycbi6o6Yz+hPayEPBq3lCGDHbAnacbjhG0v8tn3qxjLCDII0r1cINOYH3g7IJSauRur2dVTKiAWsKwW3OMuuYUq0a/wdSg3piskrSQEe9YEj3lZRG4OybuKvPiz0dYNojLmLhn4iZ7hxnvGmTDGzEassLrPCH0UYe7pAYYifsGX0IEZ3FQZfbxx7XUA9MXWXnsuWoAQLAkVDwYnbgfZOXI9jnRFJLdAMelgJ/axctjNMin1/khP755LF7zOnKYMrSOqbHCHhP1EzH/GZr3cVss6gT3vuqmkLwCkaYfIY3jFSzstk6U+YF86WYCX0efTml+qfREYDUlArCYpHS7CllGm6mmyzUG8Xz3IrsudOV/3lb824eNLkCfp8pyLuhM86BxPsxo1WiME0ED/xRkgO3AielbIWBit/AOVZd0cCwNckCw==
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: watergate-repo-creds
      namespace: argocd

---
apiVersion: v1
kind: Secret
metadata:
  name: home
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: home
  server: https://kubernetes.default.svc
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/GipsyLogic/looksrare.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: looksrare
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/GipsyLogic/gipsyanalyser.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: gipsyanalyser
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/1ndistinct/authapi.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: authapi
  namespace: argocd
type: Opaque

---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/1ndistinct/llama.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: llama
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/1ndistinct/aws-resource-manager.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: aws-resource-manager
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/1ndistinct/tekkit2.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: tekkit2
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/1ndistinct/documentation.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: documentation
  namespace: argocd
type: Opaque

---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/thewatergategroups/benjamin.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: benjamin
  namespace: argocd
type: Opaque

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Deployed Apps
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  # - https://github.com/1ndistinct/topical.git
  - https://github.com/1ndistinct/llama.git
  - https://github.com/GipsyLogic/gipsyanalyser.git
  - https://github.com/GipsyLogic/looksrare.git
  - https://github.com/1ndistinct/authapi.git
  - https://github.com/1ndistinct/tekkit2.git
  - https://github.com/1ndistinct/aws-resource-manager.git
  - https://github.com/1ndistinct/documentation.git
  # - https://github.com/1ndistinct/todo-ui.git
  - https://github.com/thewatergategroups/benjamin.git
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, */*, allow
    p, role:admin, clusters, *, */*, allow
    p, role:admin, repositories, *, */*, allow

    p, role:standard, applications, get, apps/*, allow
    p, role:standard, applications, update, apps/*, allow
    p, role:standard, applications, create, apps/*, allow
    p, role:standard, applications, delete, apps/*, allow

    p, role:readonly, applications, get, apps/*, allow

  policy.default: role:readonly

  scopes: '[groups]'

# This part maps the IDP groups to the Argo CD roles
  rbac.groups: |
    g, admin, role:admin
    g, standard, role:standard
    g, readonly, role:readonly
