apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml