apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argo
  namespace: argocd
spec:
  interval: 5m
  url: https://argoproj.github.io/argo-helm

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  chart:
    spec:
      chart: argo-cd
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
---
apiVersion: v1
kind: Secret
metadata:
  name: kind-kind
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kind-kind
  server: https://kubernetes.default.svc
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/local-development.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: local-development
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/vpn-frontend.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: vpn-frontend
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/keycloak.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: keycloak
  namespace: argocd
type: Opaque
