apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/llama
    repoURL: 'https://github.com/thewatergategroups/llama.git'
    targetRevision: main
  project: apps
