apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-documentation
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/documentation"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-benjamin
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/benjamin"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-minecraft
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/minecraft"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-auth
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/auth"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-aws-resource-manager
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/aws-resource-manager"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd-llama
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: argocd-config
  path: "./deployments/home/argo/apps/llama"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
