apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '58.7.2'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:

    grafana:
      enabled: false

      # TODO: Integrate with SealedSecrets
      adminPassword: "your-secure-password"
      # admin:
      #   existingSecret: grafana-admin-password
      #   existingSecretKey: password

      persistence:
        enabled: false
        storageClassName: rook-cephfs
        accessModes: ["ReadWriteOnce"]
        size: "20Gi"
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local
          jsonData:
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: '1'

    prometheus:
      prometheusSpec:
        retention: "3d"  # Retain metrics for 3 days
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-cephfs
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: "20Gi"

    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    # # Custom exporters can be added here
    # additionalServiceMonitors:
    #   - name: custom-exporter
    #     selector:
    #       matchLabels:
    #         app: custom-exporter
    #     endpoints:
    #       - port: "metrics"