apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '58.7.2'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  valuesFrom:
  - kind: ConfigMap
    name: flux-kube-state-metrics-config
    valuesKey: kube-state-metrics-config.yaml

  values:
    grafana:
      enabled: true

      # TODO: Integrate with SealedSecrets
      adminPassword: "UFta6ypg.qFK"
      # admin:
      #   existingSecret: grafana-admin-password
      #   existingSecretKey: password

      persistence:
        enabled: true
        storageClassName: rook-cephfs
        accessModes: ["ReadWriteOnce"]
        size: "20Gi"

      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.monitoring.svc.cluster.local
          jsonData:
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: '1'

      sidecar:
        dashboards:
          enabled: true

    prometheus:
      prometheusSpec:
        retention: "3d"  # Retain metrics for 3 days
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: rook-cephfs
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: "20Gi"

    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true

    # TODO: These dashboard imports dont work https://github.com/thewatergategroups/fluxcd/issues/45
    # dashboards:
    #   loki-overview:
    #     gnetId: 11074
    #     revision: 1
    #     datasource: Loki
    #   nginx-ingress-controller:
    #     gnetId: 9614
    #     revision: 1
    #     datasource: Prometheus
    #   cert-manager:
    #     gnetId: 9628
    #     revision: 1
    #     datasource: Prometheus
