apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keda
  namespace: flux-system
spec:
  interval: 0m30s
  path: "./deployments/home/keda"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m0s
  retryInterval: 0m30s
  prune: true
  force: true
