
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wireguard
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.truecharts.org/
# https://artifacthub.io/packages/helm/truecharts/wg-easy?modal=install