apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: snapshot-controller
spec:
  chart:
    spec:
      chart: snapshot-controller
      version: "2.2.1"  
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: snapshot-controller