apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  interval: 1m
  chart:
    spec:
      chart: wg-easy
      version: '3.0.8'
      sourceRef:
        kind: HelmRepository
        name: wireguard
        namespace: flux-system
