apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: benjamin
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/benjamin
    repoURL: 'https://github.com/thewatergategroups/benjamin.git'
    targetRevision: dev
  project: apps
