apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: wireguard
#   namespace: wireguard
# spec:
#   releaseName: wireguard
#   interval: 1m
#   chart:
#     spec:
#       chart: wg-easy
#       version: '3.0.8'
#       sourceRef:
#         kind: HelmRepository
#         name: wireguard
#         namespace: flux-system
#   values:
#     workload:
#       main:
#         podSpec:
#           containers:
#             main:
#               env:
#                 WG_HOST: "2.219.138.110"
#                 WG_MTU: 1420
#                 WG_DEVICE: enp3s0
#                 WG_PERSISTENT_KEEPALIVE: 0
#                 WG_DEFAULT_DNS: "1.1.1.1,8.8.8.8,8.8.4.4"
#                 WG_ALLOWED_IPS: "0.0.0.0/0, ::/0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    meta.helm.sh/release-name: wireguard
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - image: linuxserver/wireguard:latest
          name: wireguard
          ports:
            - containerPort: 51820
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
        - image: ngoduykhanh/wireguard-ui:latest
          name: wireguard-ui
          ports:
            - containerPort: 5000
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-external
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: vpn
      port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 31500
    - name: vpn
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31501
---