apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    meta.helm.sh/release-name: wireguard
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - image: linuxserver/wireguard:latest
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wireguard-pv
          name: wireguard
          envFrom:
            - secretRef:
                name: wireguard
          ports:
            - containerPort: 51820
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
        - image: ngoduykhanh/wireguard-ui:latest
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wireguard-pv
          name: wireguard-ui
          envFrom:
            - secretRef:
                name: wireguard
          ports:
            - containerPort: 5000
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
      volumes:
      - name: wireguard-pv
        persistentVolumeClaim:
          claimName: wireguard-pv
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-external
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: vpn
      port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 31500
    - name: ui
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31501
---
# Source: llama/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: wireguard
type: Opaque
data:
  WGUI_MANAGE_RESTART: dHJ1ZQ==
  WGUI_MANAGE_START: dHJ1ZQ==
  WGUI_PASSWORD: cGFzc3dvcmQ=
  WGUI_USERNAME: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
