apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: wireguard
spec:
  releaseName: wireguard
  interval: 1m
  chart:
    spec:
      chart: wg-easy
      version: '3.0.8'
      sourceRef:
        kind: HelmRepository
        name: wireguard
        namespace: flux-system
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WG_HOST: "2.219.138.110"
                WG_MTU: 1420
                WG_DEVICE: enp3s0
                WG_PERSISTENT_KEEPALIVE: 0
                WG_DEFAULT_DNS: "1.1.1.1,8.8.8.8,8.8.4.4"
                WG_ALLOWED_IPS: "0.0.0.0/0, ::/0"