### https://unix.stackexchange.com/questions/607004/cant-access-services-on-server-using-its-public-ip-after-starting-wireguard
### How to get internet access
#### POST UP: sysctl -w -q net.ipv4.ip_forward=1;iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;  ip rule add from 10.252.1.0/24 lookup main
#### POST DOWN:  sysctl -w -q net.ipv4.ip_forward=0;  iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE;  ip rule del from 10.252.1.0/24 lookup main
apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - image: linuxserver/wireguard:latest
          volumeMounts:
            - mountPath: /config
              name: wireguard-pv
          name: wireguard
          envFrom:
            - secretRef:
                name: wireguard
          ports:
            - containerPort: 51820
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
      volumes:
      - name: wireguard-pv
        persistentVolumeClaim:
          claimName: wireguard-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-ui
  namespace: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard-ui
  template:
    metadata:
      labels:
        app: wireguard-ui
    spec:
      restartPolicy: Always
      containers:
        - image: ngoduykhanh/wireguard-ui:latest
          volumeMounts:
            - mountPath: /etc/wireguard
              name: wireguard-pv
            - mountPath: /app/db
              name: wireguard-ui-db
          name: wireguard-ui
          envFrom:
            - secretRef:
                name: wireguard
          ports:
            - containerPort: 5000
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - SYS_MODULE
            privileged: true
      volumes:
      - name: wireguard-pv
        persistentVolumeClaim:
          claimName: wireguard-pvc
      - name: wireguard-ui-db
        persistentVolumeClaim:
          claimName: wireguard-ui-db
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-external
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    - name: vpn
      port: 51820
      protocol: UDP
      targetPort: 51820
      nodePort: 31500

---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-ui-external
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard-ui
  ports:
    - name: ui
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 31502
---
# Source: llama/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: wireguard
type: Opaque
data:
  WGUI_PASSWORD: cGFzc3dvcmQ=
  WGUI_USERNAME: YWRtaW4=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
spec:
  storageClassName: rook-cephfs
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-ui-db
spec:
  storageClassName: rook-cephfs
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
