apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: documentation
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/documentation
    repoURL: 'https://github.com/thewatergategroups/documentation.git'
    targetRevision: main
  project: apps
