apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argoced-infra
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: infrastructure
  path: "./apps/kind-kind/argocd-infra"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  timeout: 5m0s
