apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: external-secrets
      version: "<chart version here>"  # Specify the version you want to deploy
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
  values:
    installCRDs: true
    logLevel: info
    serviceAccount:
      create: true
