apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: "2.14.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  values:
    watchNamespace: ""  # Leave empty to watch all namespaces
