---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgC5bg0ZTMb6/bhqrSY9PjhBaL/ZVKFuDPtHRUcuqUkDX6vV16yexC4DeNfdPExPvuseUNzVwpH7fSNP6bN++RLJj8FtfBHwf4wU8RDv4LfM1axjQqo2Qf0PwI01z9VyRPd0HV0NA7CRlj4pS9SAXNRI9P5fUYGxHUGor2v0Z84o4UvOW+BNRFZDOtJZFgdTCe6BETeOm6z1p3DP8nPdl/5IJlUdgFZE/YX/yUcbovQjoITAyzdmKea08AgRyU6fm9+kpgyisq3QQX+j69d2Uw1zfRxecNNBoGGMf03/PerwDvHPy0ATXTuwwZog4M/IJG9K+cnpVEVdBbNz6GU2lgmwXiwm7PvPC6fYZNwwM9bbzsDpCFpmKlE4BJu0av2F2RfmycvcFeprEHvo2YQapVF+EaegFr9mDbyhehO5FuwOPM8utLoXNKevuHAnK1C3UXRlFByJvQJwO+krdkFHm2uKzFypNy9ef07Y53VFuJTi13MM5O2iM2PsruWpwTUO/ZKzaqMWAnMA9UeeEOFTmVIK8AisQSBppKKYeBjek44Ma1NAHplgbU+RwnfGyZSy0Ks7L+XJpQt+z4o+AOJu9Z/Amfbv77DB/+Iu05t9ECf+2d6K8uNRpoDVFYh4oYUm3pcGC7pyX1vKceFeCHxziHvweFYv7c2jHzoBmnQVFfLeTOCsLbCRyLaLfjBdmWeiD83t0URUikgWoEscyLySuyY8C3FuHkYw5pPRafgaMnRF2XBI8hi3ELmD7Ugyc2Fgc0vEI4z2pgrV/f/bvZHSeXiC7YWJbbgZi43zZdqEUrpYNKOBgd5Yl3IBiUthF1ebXP/4wEd+yLcHAoXRx/oD2pU=
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-values
  namespace: velero
data:
  values.yaml: |
    configuration:
      features: EnableCSI
      defaultVolumesToFsBackup: true
      backupStorageLocation:
        - name: default
          provider: aws
          bucket: infrastructure-staging-euw2-cluster-backup-732617013467
          prefix: velero
          config:
            region: eu-west-2
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: eu-west-2
    credentials:
      existingSecret: velero-credentials
    deployNodeAgent: true
    schedules:
      weekly-backup:
        disabled: false
        schedule: "45 6 * * 4"
        useOwnerReferencesInBackup: true
        template:
          ttl: "720h"
          storageLocation: default
          snapshotVolumes: true
          includeClusterResources: true
          volumeSnapshotLocations:
            - default
          includedNamespaces:
          - "*"
    initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.9.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: cephfs-snapclass
driver: rook-ceph.cephfs.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: rook-ceph
  csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 1m
  chart:
    spec:
      chart: velero
      version: "6.0.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
