apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1m
  chart:
    spec:
      chart: external-secrets
      version: '0.9.16'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus
