apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo
  namespace: argocd
spec:
  interval: 5m
  path: "./argocd"
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: argocd-server
      namespace: argocd
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argo
  namespace: argocd
spec:
  dependsOn:
    - name: argo
  interval: 5m
  path: "./dependencies"
  prune: true