apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  releaseName: metrics-server
  interval: 1m
  chart:
    spec:
      chart: metrics-server
      version: '3.12.1'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  # values:
