apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  url: https://github.com/argoproj/argo-helm
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  releaseName: argocd
  chart:
    spec:
      chart: charts/argo-cd
      sourceRef:
        kind: GitRepository
        name: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: kind-kind
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kind-kind
  server: https://kubernetes.default.svc
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/local-development.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: local-development
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/vpn-frontend.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: vpn-frontend
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/keycloak.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: keycloak
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/topical.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: topical
  namespace: argocd
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Dev project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/Wednesday-Vibes/topical.git
  - https://github.com/Wednesday-Vibes/keycloak.git
  - https://github.com/Wednesday-Vibes/vpn-frontend.git
  - https://github.com/Wednesday-Vibes/local-development.git
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
