apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  url: https://github.com/argoproj/argo-helm
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  releaseName: argocd
  chart:
    spec:
      chart: charts/argo-cd
      sourceRef:
        kind: GitRepository
        name: argocd
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: kind-kind
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: kind-kind
  server: https://kubernetes.default.svc
---
apiVersion: v1
stringData:
  type: git
  url: https://github.com/Wednesday-Vibes/local-development.git
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: local-development
  namespace: argocd
type: Opaque

