apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: argo
  namespace: argocd
spec:
  interval: 5m
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: argocd-server
      namespace: argocd
resources:
- argocd.yaml

---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
metadata:
  name: argo
  namespace: argocd
spec:
  dependsOn:
    - name: argo
  interval: 5m
  prune: true
resources:
- dependencies.yaml