apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- dependencies.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argo
  namespace: argocd
spec:
  sourceRef:
    kind: HelmRelease
    name: argocd
  path: ./
  prune: true
  wait: true
  timeout: 5m