apiVersion: v1
kind: Namespace
metadata:
  name: openvpn
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: openvpn
spec:
  releaseName: openvpn
  interval: 1m
  chart:
    spec:
      chart: openvpn
      version: '0.1.1'
      sourceRef:
        kind: HelmRepository
        name: openvpn
        namespace: flux-system
  values:
    host: 84.65.119.87 
    github_team: Wednesday-Vibes/Noobs