apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.ciaran.clientSecret: AgBsyYPKDvam1rOg7pMY2N7wxgW18xoxXV8OaoC62qt66w6R/+Gfu0+OJBUswMGf4DcLmvvhTHITeVnmGcSU60lyEcBnrHeUc+NuLuBftIV/sXK4x5AZCOz1xEqaOHGNyDvR2VbMFt+aWDDxzoILHjitvisP9GxzSivB0gAc/FUYnMqg7WRZanueQkYc3jzs2DhB1LwkDk0NTfdCMIc+GUj07M/QyqUwAcMn+YGqlf2dD7i+5DZ1ziWTtyLUpWuFKNlstJrbtfyaBo+s2CkJFHUt4Hqoc+670eHvy8ZTGfmstP7nrhCiGnWnJMG7S8EnKIN2U3+Ielbq9zuLExml2WzIKISZ9jSCpqlKxb46QJwWqj0wmT3PPrnuXCALdW+a9ZhpEkKhkanMo3fYhNWgW41MT4/RFSEknvyTMjJrW1LG7T2mT3lCbmigXnHUWUd/+Le8UaJ/AZj1uKDMrYeci8w236/QNXmg8j4HUfz1z2Epz9SFzGXT1UXVvJz+Lt/dJIzUUfcKTO45W6YREG7IAlDeyglTu3Ii9FhZ4ew/inVqqVbbJ42R5LgH9Fg9l0f6R1PqVcTUpzCnnUHXBje+8q4Bkrjk6Ch4IVPc0AYhPMkMGE8yReT3I8QUvGbJYoN785Q84TApTguCivmUmWn+KyJeAh+sB22KhPDbhsfbO83XE6H1ub4YOhu1/wOygK4lta5ZoUW9k99Rb7qHC2tNYVUqenC4ZIZ0LdK4rr7iW714dCBymQXFm3IJfHhx
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
    type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  interval: 1m
  chart:
    spec:
      chart: argo-cd
      version: '5.19.12'
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    timeout: 30s
    remediation:
      retries: 1
      strategy: rollback
  values:
    global:
      domain: argocd.thewatergategroups.com
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: argocd.thewatergategroups.com
          external-dns.alpha.kubernetes.io/cname-target: thewatergategroups.com
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          kubernetes.io/ingress.class: nginx
        hosts:
          - argocd.thewatergategroups.com
        tls:
          - hosts:
            - argocd.thewatergategroups.com
            secretName: wildcard-watergate-tls
      service:
        type: ClusterIP
        servicePortHttps: 443
        servicePortHttp: 80
    configs:
      params:
        server.insecure: true
      cm: 
        admin.enabled: false
        url: https://argocd.thewatergategroups.com
        oidc.config: |
              name: Ciaran
              issuer: https://auth.thewatergategroups.com
              clientID: 94221717-e022-4d82-b90d-e83fece477c9
              clientSecret: $argocd-oidc-secret:oidc.ciaran.clientSecret
              requestedScopes:
                - openid
                - profile
                - email
                - groups
              getUserInfo: true