apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/storage
    repoURL: 'https://github.com/1ndistinct/storage.git'
    targetRevision: main
  project: apps
