apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 0m30s
  dependsOn:
    - name: infrastructure
  path: "./apps/home/postgres-operator"
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true # wait for all applied resources to become ready
  timeout: 5m0s # give up waiting after three minutes
  retryInterval: 0m30s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: true # enable this to recreate resources on immutable fields changes
