apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  releaseName: argocd
  interval: 1m
  chart:
    spec:
      chart: argo-cd
      version: '5.19.12'
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system

