apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  releaseName: rook-ceph
  interval: 1m
  chart:
    spec:
      chart: rook-ceph
      version: '1.13.2'
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
  install:
    remediation:
      retries: 1
  upgrade:
    timeout: 30s
    remediation:
      retries: 1
      strategy: rollback
  values:
    csi:
      enableCephfsDriver: true
      enableCephfsSnapshotter: true
      # enablePluginSelinuxHostMount: true
      kubeletDirPath: "/var/snap/microk8s/common/var/lib/kubelet"
      enableRbdDriver: false
      enableRBDSnapshotter: false
      enableNFSSnapshotter: false
      provisionerReplicas: 1
      clusterName: rook-ceph
