apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-exporter
  namespace: rook-ceph-namespace
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph-namespace
  selector:
    matchLabels:
      app: rook-ceph-exporter
  endpoints:
    - port: ceph-exporter-http-metrics
      path: /metrics
      interval: 10s


-----

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: rook-ceph-namespace
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph-namespace
  selector:
    matchLabels:
      app: csi-metrics
  endpoints:
    - port: csi-http-metrics
      path: /metrics
      interval: 10s # 5s by default/recommended
