apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: polaris
  namespace: polaris
spec:
  interval: 5m
  chart:
    spec:
      chart: polaris
      version: "5.17.1"
      sourceRef:
        kind: HelmRepository
        name: polaris-repo
        namespace: flux-system
  values:
    dashboard:
      enable: true
    webhook:
      enable: true
    rbac:
      create: true
