apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: polaris
  namespace: polaris
spec:
  interval: 5m
  chart:
    spec:
      chart: polaris
      version: "5.17.1"
      sourceRef:
        kind: HelmRepository
        name: polaris-repo
        namespace: flux-system
  values:
    dashboard:
      enable: true
    webhook:
      enable: false # Disable webhook for admission controller
    rbac:
      create: true
    serviceAccount:
      create: true
      name: polaris
    audit:
      config:
        exemptNamespaces:
          - kube-system
          - polaris
    scanner:
      intervalSeconds: 300
      # excludeChecks: # Example
      #   - "hostNetwork"
      #   - "hostPID"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
