apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-udp
  namespace: external-endpoint
data:
  51820: "apps/wireguard:51820"
---
# nginx-ingress-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: external-endpoint
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      extraArgs:
        udp-services-configmap: "external-endpoint/wireguard-udp"
      service:
        loadBalancerIP: 192.168.0.76
      replicaCount: 2
      metrics:
        enabled: false
      admissionWebhooks:
        enabled: false
