apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgBOISb84sKLiirRBYyo/mLPZuXybfPI/Q1uSVGaR6ACjrGa2nzFslDnBC0OJdPKBfpK++TNb/hb24+BKN3u4ytOp40Y3rmrv0kZ1o+f91xoKEISjikTmSrZ0mqrn44zvgO0qTscMXJOZ9fgDq/NLiQk4kHDfnHcoqXNkvi58nEIsSPg1mHxydW6b0m7ktIU3gNTiK2VvONrDBw9K15ilw+yV0Gd3gM3SdhVmZGfL+Pv3XNBNk4T4Q6RTjNLEQpb58EfPIFoxCdGUEAF46Frlp45PMMOFFMPorJ1A/mKsFaUkpywqdGFbOyXQ+uNiXN/S3bAVw18ChUqudPNl/BgQfWbnO5rzK8EdeqVSMGVOWYMq6UWD+5c82asejYCMHlH1eG5TUgOSrb0RXmt7S3mpvJmN4qy7VSRw+AFIV+5q5hfvmcu1GT8zXkJuMTMiTOw55+9G7608t7K7kDgcRm5alMgFCOYboPlJcDK6+kiRwPG5k4IyurYNNP2QdP+4/uMtgS1q6zwCHYU46ssvKDRmSJQbJ+nBYZ6CK47HI/s31sQnQujj5cpOr6YubomDPSQlsMXjwe9md9OAOAKNvv10ac3m+tb+0ThQkTcm4BvJZj565qYnHYGV3vwblu2Pf9dYb5kBAr4p6e3rt6SDmQMwtaAz5Thl0B0RYvss+o9+oebSeRC0OGuhv6gAOmE1WoXyrXZvK+qM77xIPVn/wP8T3gJsLwdZGav72678eZQ+L8ra9b0FvuWAq3YWnJ1b+mQltWIEN7z3XrzMGqAWrsLHbqABeKq9zRrvcPC9oZO9QQRdXhfjEawlVez4LBr+hPkVsc9MxoYB8SdCsHvutpG9cVBpKlY0uG+GJtfeTkiP/hN8JcoCbdnAIoB0t8QdqR6NG+9iLPoBoTMvHGcOaKMXl9bgzHcqL3VEQQe+PZy/uLXJwBOVuJ89XIygw70tIaZUs5a92J3J8XYhoymkXSHJE4QUFURWBZjUkJkUhTCb1vnZ20ljycJ
  template:
    metadata:
      name: regcred
      namespace: apps
    type: kubernetes.io/dockerconfigjson
