apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin  
  namespace: apps
spec:
  releaseName: pgadmin
  interval: 1m
  chart:
    spec:
      chart: pgadmin4
      version: '1.18.5'
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
  values:
    tolerations:
    - key: networkmode
      operator: Equal
      value: host
      effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: networkmode
              operator: In
              values:
              - host  
    persistentVolume:
      size: 100Mi
      storageClass: nfs
      accessModes: ["ReadWriteMany"]
    service:
      type: NodePort
      nodePort: 31001

