apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin  
  namespace: apps
spec:
  releaseName: pgadmin
  interval: 1m
  chart:
    spec:
      chart: pgadmin4
      version: '1.18.5'
      sourceRef:
        kind: HelmRepository
        name: runix-charts
        namespace: flux-system
  values:
    persistentVolume:
      enabled: false
    envVarsExtra:
      - name: PGADMIN_CONFIG_SERVER_MODE
        value: 'False'
      - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
        value: 'False'
