apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ciaranmckey@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          route53:
            region: "eu-west-2"
            accessKeyIDSecretRef:
              name: domain-management-creds
              key: aws_access_key_id
            secretAccessKeySecretRef:
              name: domain-management-creds
              key: aws_secret_access_key
            hostedZoneID: "Z061744026X1CUF71V2PH"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-watergate-certificate
  namespace: apps
spec:
  secretName: wildcard-watergate-tls-apps
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: '*.thewatergategroups.com'
  dnsNames:
    - '*.thewatergategroups.com'
    - thewatergategroups.com
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-watergate-certificate-argocd
  namespace: argocd
spec:
  secretName: wildcard-watergate-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: '*.thewatergategroups.com'
  dnsNames:
    - '*.thewatergategroups.com'
    - thewatergategroups.com
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment
    - server auth
